version: '3'

volumes:
  pg_data:

services:
  steam-db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  tg_bot:
    build: ./
    env_file: .env
    depends_on:
      - steam-db